# Generated by Django 4.1.7 on 2023-08-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='distrito',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posto',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='provincia',
            new_name='province',
        ),
    ]
