# Generated by Django 4.1.7 on 2023-08-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_distrito_post_district_rename_posto_post_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
