# Generated by Django 4.1.7 on 2023-08-17 19:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('district', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
