# Generated by Django 4.1.7 on 2023-08-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
