# Generated by Django 4.1.7 on 2023-08-18 00:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_district_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id_project_area', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('territory_level', models.CharField(choices=[('Nacional', 'Nacional'), ('Provincial', 'Provincial'), ('Distrital', 'Distrital'), ('Posto Administrativo', 'Posto Admnistrativo'), ('Menor que Posto Administrativo', 'Menor que Posto Administrativo')], max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='project',
            name='district',
        ),
        migrations.RemoveField(
            model_name='project',
            name='province',
        ),
        migrations.RemoveField(
            model_name='project',
            name='town',
        ),
    ]
