# Generated by Django 4.1.7 on 2023-08-18 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectarea_rename_data_added_project_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarea',
            name='project_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
