# Generated by Django 4.1.7 on 2023-07-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('id_employee', models.ForeignKey(blank=True, db_column='id_employee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
                ('id_project', models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
        ),
    ]
