# Generated by Django 4.1.7 on 2023-07-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business', models.CharField(blank=True, max_length=200, null=True)),
                ('duat', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('work_start', models.TimeField(blank=True, null=True)),
                ('work_close', models.TimeField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('company_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('id_project', models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
    ]
